scan_filter_chain:
- name: range
  type: LaserScanRangeFilter
  params:
    lower_threshold: 0.2
    upper_threshold: .inf
- name: angle
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.0472
    upper_angle:  1.0472
